name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Persist /.npm
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Persist /.cache
        uses: actions/cache@v5
        with:
          path: ./.cache
          key: ${{ runner.os }}-eleventy-fetch-cache

      - name: Build site
        run: npm install && npm run build-ghpages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/
  
  deploy:
    needs: build
    runs-on: ubuntu-slim
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4